import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../core/auth.service';
import { ApiService } from '../core/api.service';
import { Address, AddressInput, Customer } from '../models';
import { errorMessage } from '../core/format';

@Component({ imports:[FormsModule], changeDetection:ChangeDetectionStrategy.OnPush, template:`
  <section class="shell py-14"><div class="flex flex-wrap items-end justify-between gap-5"><div><p class="eyebrow text-rust">Your account</p><h1 class="mt-3 font-display text-6xl font-bold">Hello, {{customer()?.first_name || auth.displayName()}}.</h1></div><div class="flex gap-2"><button class="btn btn-secondary" (click)="auth.accountManagement()">Keycloak settings</button><button class="btn btn-primary" (click)="auth.logout()">Sign out</button></div></div>
  @if(error()){<div class="mt-8 rounded-xl bg-rust/10 p-4 text-rust">{{error()}}</div>}
  @if(customer();as profile){<div class="mt-10 grid gap-8 lg:grid-cols-2"><section class="panel p-7"><h2 class="font-display text-3xl font-bold">Profile</h2><dl class="mt-6 grid gap-4"><div><dt class="eyebrow text-ink/45">Name</dt><dd class="mt-1">{{profile.first_name}} {{profile.last_name}}</dd></div><div><dt class="eyebrow text-ink/45">Email</dt><dd class="mt-1">{{profile.email}}</dd></div><div><dt class="eyebrow text-ink/45">Customer ID</dt><dd class="mt-1 break-all font-mono text-sm">{{profile.id}}</dd></div><div><dt class="eyebrow text-ink/45">Keycloak user ID (sub)</dt><dd class="mt-1 break-all font-mono text-sm">{{profile.keycloak_user_id}}</dd></div></dl><p class="mt-6 text-sm text-ink/55">Name and email are managed by Keycloak and synchronized when this profile is loaded.</p></section>
  <section class="panel p-7"><div class="flex items-center justify-between"><h2 class="font-display text-3xl font-bold">Addresses</h2><button class="btn btn-secondary !min-h-9 !py-1" (click)="newAddress()">Add</button></div>@if(!addresses().length){<p class="mt-6 text-ink/60">No shipping address saved yet.</p>}@for(address of addresses();track address.id){<article class="mt-5 rounded-xl border border-ink/10 bg-white/60 p-5"><div class="flex justify-between gap-3"><address class="not-italic leading-6">{{address.street}}<br>{{address.zip_code}} {{address.city}}<br>{{address.country}}</address>@if(address.is_default){<span class="h-fit rounded-full bg-moss/10 px-2 py-1 text-xs font-bold text-moss">Default</span>}</div><div class="mt-4 flex gap-4 text-sm font-bold"><button (click)="editAddress(address)">Edit</button><button class="text-rust" (click)="removeAddress(address)">Delete</button></div></article>}</section></div>}
  @if(editing()){<div class="fixed inset-0 z-50 grid place-items-center bg-ink/45 p-4" (click)="closeEditor()"><form class="panel w-full max-w-lg p-7" (submit)="saveAddress();$event.preventDefault()" (click)="$event.stopPropagation()"><h2 class="font-display text-3xl font-bold">{{editingId()?'Edit':'Add'}} address</h2><div class="mt-6 grid gap-4"><label>Street<input class="field mt-1" required name="street" [(ngModel)]="form.street"></label><div class="grid grid-cols-[8rem_1fr] gap-3"><label>Postal code<input class="field mt-1" required name="zip" [(ngModel)]="form.zip_code"></label><label>City<input class="field mt-1" required name="city" [(ngModel)]="form.city"></label></div><label>Country code<input class="field mt-1 uppercase" required maxlength="2" name="country" [(ngModel)]="form.country"></label><label class="flex gap-2"><input type="checkbox" name="default" [(ngModel)]="form.is_default"> Use as default address</label></div><div class="mt-7 flex justify-end gap-2"><button type="button" class="btn btn-secondary" (click)="closeEditor()">Cancel</button><button class="btn btn-primary" [disabled]="saving()">{{saving()?'Saving…':'Save address'}}</button></div></form></div>}
  </section>` })
export class AccountComponent {
  readonly auth=inject(AuthService);private readonly api=inject(ApiService);readonly customer=signal<Customer|null>(null);readonly addresses=signal<Address[]>([]);readonly error=signal('');readonly editing=signal(false);readonly editingId=signal<string|null>(null);readonly saving=signal(false);form:AddressInput={street:'',city:'',zip_code:'',country:'DE',is_default:false};
  constructor(){this.load();} load(){this.api.me().subscribe({next:c=>{this.customer.set(c);this.loadAddresses()},error:e=>this.error.set(errorMessage(e))})}loadAddresses(){this.api.addresses().subscribe({next:a=>this.addresses.set(a),error:e=>this.error.set(errorMessage(e))})}
  newAddress(){this.form={street:'',city:'',zip_code:'',country:'DE',is_default:!this.addresses().length};this.editingId.set(null);this.editing.set(true)} editAddress(a:Address){this.form={street:a.street,city:a.city,zip_code:a.zip_code,country:a.country,is_default:a.is_default};this.editingId.set(a.id);this.editing.set(true)}closeEditor(){this.editing.set(false)}
  saveAddress(){this.saving.set(true);const request=this.editingId()?this.api.updateAddress(this.editingId()!,this.form):this.api.createAddress(this.form);request.subscribe({next:()=>{this.saving.set(false);this.closeEditor();this.loadAddresses()},error:e=>{this.saving.set(false);this.error.set(errorMessage(e))}})}
  removeAddress(a:Address){if(!confirm(`Delete ${a.street}?`))return;this.api.deleteAddress(a.id).subscribe({next:()=>this.loadAddresses(),error:e=>this.error.set(errorMessage(e))})}
}
